config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get "/movies/:id/edit", to: "movies#edit"
  patch "/movies/:id", to: "movies#update"
  get "/movies", to: "movies#index"
  get "/movies/:id", to: "movies#show"
  delete "/movies/:id", to: "movies#destroy"

  get "/directors", to: "directors#index"
  get "/directors/:id/edit", to: "directors#edit"
  patch "/directors/:id", to: "directors#update"
  post "/directors", to: "directors#create"
  get "/directors/new", to: "directors#new"
  get "/directors/:id", to: "directors#show"
  delete "/directors/:id", to: "directors#destroy"

  get "/directors/:id/movies", to: "director_movies#index"
  get "/directors/:id/movies/new", to: "director_movies#new"
  post "/directors/:id/movies", to: "director_movies#create"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/director.rb
class Director < ApplicationRecord 
  has_many :movies, dependent: :destroy

  validates :name, format: { with: /[a-zA-Z]/ }
  validates :years_active, numericality: { only_integer: true }
  validates :best_director, inclusion: [true, false]
  validates :name, :years_active, presence: true

  def format_name 
    name_arr = name.split(", ")
    len = name_arr.length - 2
    "#{name_arr.last} #{name_arr.slice(0..len).join(" ").delete(",")}"
  end

  def movie_count 
    movies.count
  end

  def self.sort_by(type) 
    # does not return directors with '0' movies associated
    if type == "count" 
      select("directors.*, COUNT(movies.id) AS movie_count")
        .joins(:movies)
        .group("directors.id")
        .order("movie_count DESC")
    end
  end

  def self.sort_by_created_at 
    select("directors.*").order("created_at DESC")
  end

  def self.find_count(n)
    director_counts = select("directors.*, COUNT(movies.id) AS movie_count").joins(:movies).group("directors.id")
    director = director_counts.find do |director|
      director.movie_count == n.to_i
    end
    return [director] if director
    return []
  end
  
  def self.find_exact(name)
    director = select("directors.*").where("name = ?", name)

    return director if director 
    return []
  end

  def self.find_partial(name)
    result_arr = []
    name_arr = name.split(" ")
    if name_arr.length >= 1
      name_arr.each do |name| 
        director = select("directors.*").where("name ILIKE ?", "%#{name.delete(",")}%")
        return director if director.length >= 1
        return []
      end
    else
      return Director.all
    end
  end
  
end

app/models/movie.rb
class Movie < ApplicationRecord 
  belongs_to :director
  
  validates :title, format: { with: /[a-zA-Z]/ }, presence: true
  validates :rating, format: { with: /(g|pg|[pg\-13]|r)/i }, presence: true
  validates :released, numericality: { only_integer: true }, presence: true
  # TODO why are valid values returning 'false' in being present?
  validates :sex, :nudity, :violence, inclusion: { in: [true, false] }, allow_blank: false
  # validates :sex, :nudity, :violence, presence: true, allow_blank: false
  

  validates_length_of :released, minimum: 0, maximum: Time.now.year

  enum rating: { "G": 0, "PG": 1, "PG-13": 2, "R": 3}

  def format_title
    if title.index(",")
      t_arr = title.split(", ")
      len = t_arr.length - 2
      "#{t_arr.last} #{t_arr.slice(0..len).join(" ").delete(",")}"
    else
      return title
    end
  end

  # def self.adult_content 
  #   where("sex = true OR nudity = true")
  # end

  # def self.violence
  #   where(violence: true)
  # end

  def self.sort_movies(type)
    if type == "alpha"
      self.select("movies.*").order("title ASC")
    end
  end

  def self.mature_content
    movies = where("sex = true OR nudity = true OR violence = true")
    return movies unless movies.empty?
    return []
  end

  def self.released_after(year) 
    select("movies.*").where("movies.released > ?", year)
  end

  def self.exact_search(title)
    movie = select("movies.*").where("title = ?", title)
    return movie unless movie.empty? 
    return []
  end

  def self.partial_search(title) 
    movie = select("movies.*").where("title ILIKE ?", "%#{title}%")
    return movie unless movie.empty?
    return []
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/director_movies_controller.rb
class DirectorMoviesController < ApplicationController 
  def index 
    @director = Director.find(params[:id])
    
    if params[:sort] 
      @movies = @director.movies.sort_movies(params[:sort])
    else
      @movies = @director.movies
    end

    if params[:released_after]
      @movies = @director.movies.released_after(params[:released_after])
    end
  end

  def new 
    @director = Director.find(params[:id])
  end

  def create 
    director = Director.find(params[:id])

    movie = director.movies.new({
      title: params[:title],
      released: params[:released],
      rating: params[:rating].to_i,
      sex: params[:sex],
      nudity: params[:nudity],
      violence: params[:violence]
    })

    if movie.save
      flash[:notice] = "A new movie has been successfully added."
    else
      flash[:notice] = "Sorry, an error has ocurred. The movie was not added to the system. Please try again."
    end
    redirect_to "/directors/#{director.id}/movies"
  end

end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController 
  def index 
    if params[:sort_by] 
      @directors = Director.sort_by(params[:sort_by])
    elsif params[:find_exact] && params[:find_exact].length > 0
      @directors = Director.find_exact(params[:find_exact])
    elsif params[:find_partial] && params[:find_partial].length > 0
      @directors = Director.find_partial(params[:find_partial])
    elsif params[:find_count] && params[:find_count].length > 0
      @directors = Director.find_count(params[:find_count])
    else
      @directors = Director.sort_by_created_at
    end
  end

  def show 
    @director = Director.find(params[:id])
  end

  def new 

  end

  def create 
    director = Director.new({name: params[:name], years_active: params[:years_active], best_director: params[:best_director]})
    
    if director.save
      flash[:notice] = "New director created."
      redirect_to "/directors"
    else
      flash[:notice] = "Sorry, something went wrong. Please try again."
      redirect_to "/directors/new"
    end
  end

  def edit 
    @director = Director.find(params[:id])
  end

  def update 
    director = Director.find(params[:id])

    # Not using update! (with bang!) b/c validations stop program execution
    if director.update({name: params[:name], years_active: params[:years_active], best_director: params[:best_director]})
      flash[:notice] = "The director's bio information has been successfully updated."
      redirect_to "/directors/#{params[:id]}"
    else
      flash[:notice] = "Sorry, there was an error and the director's bio information was not updated. Please try updating again." 
      redirect_to "/directors/#{director.id}/edit"
    end
  end

  def destroy 
    Director.destroy(params[:id])

    redirect_to "/directors"
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController 
  def index 
    if params[:find_exact] && params[:find_exact].length > 0 
      @movies = Movie.exact_search(params[:find_exact])
    elsif params[:find_partial] && params[:find_partial].length > 0
      @movies = Movie.partial_search(params[:find_partial])
    else
      @movies = Movie.all
    end
  end

  def show 
    @movie = Movie.find(params[:id])
  end

  def edit 
    @movie = Movie.find(params[:id])
  end

  def update 
    movie = Movie.find(params[:id])
    director = movie.director

    if movie.update({
      title: params[:title],
      released: params[:released],
      rating: params[:rating].to_i,
      sex: params[:sex],
      nudity: params[:nudity],
      violence: params[:violence],
      director_id: director.id
    })
      flash[:notice] = "The movie has been successfully updated."
      redirect_to "/movies/#{movie.id}"
    else
      flash[:notice] = "Sorry, we were not able to update any movie data. Please try again." 
      redirect_to "/movies/#{movie.id}/edit"
    end
  end
  
  def destroy 
    Movie.destroy(params[:id])

    redirect_to "/movies"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/director_movies/index.html.erb
<h1><%= "#{@director.format_name} Movies" %></h1>
<%= link_to "Create Movie", "/directors/#{@director.id}/movies/new" %>
<%= link_to "Sort Movies", "/directors/#{@director.id}/movies?sort=alpha" %>
<% @movies.each do |movie| %>
  <article id=<%= "index-#{movie.id}" %>>
    <h3><%= movie.format_title %></h3>
    <%= link_to "edit", "/movies/#{movie.id}/edit" %>
    <p>Released: <%= movie.released %></p>
    <p>Rating: <%= movie.rating %></p>
    <p>Sex: <%= movie.sex %></p>
    <p>Nudity: <%= movie.nudity %></p>
    <p>Violence: <%= movie.violence %></p>
    <br>
  </article>
<% end %>

<h2>Filter Movies by Year Released</h2>
<%= form_with url: "/directors/#{@director.id}/movies", method: :get, data: {turbo: false}, local: true do |f| %> 
  <%= f.label "Released after" %>
  <%= f.text_field :released_after %>
  <%= f.hidden_field :button_year, value: :released_after %>
  <%= f.submit "Return movies" %>
<% end %>

app/views/director_movies/new.html.erb
<h1><%= "Add a #{@director.format_name} Movie" %></h1>
<%= form_with url: "/directors/#{@director.id}/movies", data: {turbo: false}, local: true do |f| %>
  <%= f.label "Title" %>
  <%= f.text_field :title %>
  <%= f.label "Released" %>
  <%= f.text_field :released %>
  <%= f.label "Rating" %>
  <%= f.text_field :rating %>
  <%= f.label "Sex" %>
  <%= f.text_field :sex %>
  <%= f.label "Nudity" %>
  <%= f.text_field :nudity %>
  <%= f.label "Violence" %>
  <%= f.text_field :violence %>

  <%= f.submit "Create Movie" %>
<% end  %>

app/views/directors/edit.html.erb
<h1>Update <%= "#{@director.format_name}'s Bio" %></h1>
<%= form_with url: "/directors/#{@director.id}", method: :patch, data: {turbo: false}, local: true do |f| %>
  <%= f.label "Name" %>
  <%= f.text_field :name, value:@director.name %>
  <%= f.label "Years active" %>
  <%= f.text_field :years_active, value:@director.years_active %>
  <%= f.label "Best director" %>
  <%= f.text_field :best_director, value:@director.best_director %>
  <%= f.submit "Update" %>
<% end  %>

app/views/directors/index.html.erb
<h1 style="text-decoration:underline">Director List</h1>
<%= link_to "New Director", "/directors/new" %> &nbsp&nbsp&nbsp
<%= link_to "Sort by Movie Count", "/directors?sort_by=count" %>
<% unless @directors.empty? %>
  <% @directors.each do |director| %>   
    <p id=<%= "index-#{director.id}" %>>
      <%= link_to "#{director.name}", "/directors/#{director.id}" %> &nbsp&nbsp&nbsp <%= "#{director.created_at}" %>  &nbsp <%= "Movie count: #{director.movie_count}" %> &nbsp&nbsp
      <%= link_to "edit", "/directors/#{director.id}/edit" %> &nbsp
      <%= link_to "delete", "/directors/#{director.id}", data: { turbo_method: :delete } %>
    </p>
  <% end %>
<% end %>

<%= form_with url: "/directors", method: :get, data: {turbo: false}, local: true do |f| %>
  <%= f.label "Filter by exact name:" %>
  <%= f.text_field :find_exact %>
  <%= f.label "Filter by partial name:" %>
  <%= f.text_field :find_partial %>
  <%= f.label "Filter by movie count:" %>
  <%= f.text_field :find_count %>
  <%= f.submit "Search" %>
<% end %>

app/views/directors/new.html.erb
<h1>New Director</h1>
<%= form_with url: "/directors", data: { turbo: false }, local: true do |f| %>
  <%= f.label "Name" %>
  <%= f.text_field :name %>
  <%= f.label "Years Active" %>
  <%= f.text_field :years_active %>
  <%= f.label "Best Director" %>
  <%= f.text_field :best_director %>
  <%= f.submit "Create Director" %>
<% end %>

app/views/directors/show.html.erb
<h1 style="text-decoration:underline">Director Details</h1>
<%= link_to "Update Director", "/directors/#{@director.id}/edit" %>
&nbsp | &nbsp <%= link_to "#{@director.format_name.titleize} movies", "/directors/#{@director.id}/movies" %>
<h3><%= @director.format_name %> <%= link_to "delete", "/directors/#{@director.id}", data: { turbo_method: :delete } %></h3>
<p>Movie Count: <%= @director.movie_count %>
<p>Years Active: <%= @director.years_active %></p>
<p>Best Director Oscar: <%= @director.best_director %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Netflicks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= link_to "movies", movies_path %> &nbsp | &nbsp <%= link_to "directors", directors_path %>
    <h4><%= flash[:notice] %></h4>
    <%= yield %>
  </body>
</html>

app/views/movies/edit.html.erb
<h1><%= "Edit #{@movie.title}" %></h1>
<%= form_with url: "/movies/#{@movie.id}", data: { turbo: false }, method: :patch, local: true do |f| %>
  <%= f.label "Title" %>
  <%= f.text_field :title, value: @movie.title %>
  <%= f.label "Released" %>
  <%= f.text_field :released, value: @movie.released %>
  <%= f.label "Rating" %>
  <%= f.text_field :rating, value: @movie.rating %>
  <%= f.label "Sex" %>
  <%= f.text_field :sex, value: @movie.sex %>
  <%= f.label "Nudity" %>
  <%= f.text_field :nudity, value: @movie.nudity %>
  <%= f.label "Violence" %>
  <%= f.text_field :violence, value: @movie.violence %>
  <%= f.submit "Update Movie" %>
<% end %>

app/views/movies/index.html.erb
<section id="original-index">
  <h1 style="text-decoration:underline">Movie List</h1>
  <% unless @movies.empty? %>
    <% @movies.each do |movie| %>
      <span id=<%= "movie-index-#{movie.id}"%>>
        <%= link_to "edit", "/movies/#{movie.id}/edit" %> <%= link_to "delete", "/movies/#{movie.id}", data: { turbo_method: :delete } %>
        <h3><%= link_to movie.title, "/movies/#{movie.id}" %></h3>
        <p>Released: <%= movie.released %></p>
        <p>Rating: <%= movie.rating %></p>
        <p>Sex: <%= movie.sex %></p>
        <p>Nudity: <%= movie.nudity %></p>
        <p>Violence: <%= movie.violence %></p>
        <br>
      </span>
    <% end %>
  <% end %>
</section>

<section id="index-mature-content">
  <h2 style="text-decoration:underline; margin-bottom: -10px">Movies Containing Violence or Adult Content</h2>
  <br>
  <% unless @movies.empty? %>
    <% @movies.mature_content.each do |movie| %>
      <h3 style="font-style:italic"><%= link_to movie.title, "/movies/#{movie.id}" %></h3>
      <p id=<%= "index-#{movie.id}" %> style="margin-bottom: 5px">
        <%= "Released: #{movie.released}" %>&nbsp | &nbsp<%= "Rating: #{movie.rating}" %> <%= link_to "edit", "/movies/#{movie.id}/edit" %> <%= link_to "delete", "/movies/#{movie.id}", data: { turbo_method: :delete } %>
      </p>
    <% end %>
  <% end %>
  <br>
</section>

<%= form_with url: "/movies", method: :get, data: {turbo: false}, local: true do |f| %>
  <%= f.label "Exact title search:" %>
  <%= f.text_field :find_exact %>
  <%= f.label "Partial title search:" %>
  <%= f.text_field :find_partial %>
  <%= f.submit "Search" %>
<% end %>

app/views/movies/show.html.erb
<h1 style="text-decoration:underline">Movie Details</h1>
<h3><%= @movie.format_title %></h3>
<%= link_to "Update Movie", "/movies/#{@movie.id}/edit" %>
<%= link_to "Delete Movie", "/movies/#{@movie.id}", data: { turbo_method: :delete } %>
<p>Released: <%= @movie.released %></p>
<p>Rating: <%= @movie.rating %></p>
<p>Sex: <%= @movie.sex %></p>
<p>Nudity: <%= @movie.nudity %></p>
<p>Violence: <%= @movie.violence %></p>